name: Push commit
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run benchmark
        run: date +%s > "$(date +"%Y-%m-%d_%H-%M-%S")_${GITHUB_SHA}.txt"
      - name: Commit report
        run: |
          git config --global user.name 'ci'
          git config --global user.email 'jf550-kent@users.noreply.github.com'
          git add .
          git commit -m "Automated report"
          git push