name: Run Benchmark
on: push
permissions:
  contents: write

jobs:
  benchmark:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      
      - name: Check format
        run: test -z $(go fmt ./...)

      - name: Run benchmark and write to file
        run:  |
          FILENAME="performance/$(date +"%Y-%m-%d_%H-%M-%S").txt"
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          go test ./... -bench=. -benchmem -run '^#' > "${FILENAME}"

      - name: Commit and push the 
        run: |
          git config --global user.name 'ci'
          git config --global user.email 'jf550-kent@users.noreply.github.com'
          git add -A
          git commit -m "Record performance for ${FILENAME}"
          git push
